const KEY='yom-kippur-retreat:answers:v1';
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const p=s=>`<p>${s.replace(/\n/g,'<br>')}</p>`;
function field(id,label,size='large',input=false){return `<div class="writing"><label class="sr-only" for="${id}">${label}</label>${input?`<input id="${id}" data-answer autocomplete="off" placeholder="${esc(label)}">`:`<textarea id="${id}" data-answer class="${size}" placeholder="אפשר להתחיל מכאן…"></textarea>`}</div>`;}
function group(id,title,questions,size='large',intro=''){return `<div class="question-group"><h4>${title}</h4>${intro?p(intro):''}<ul class="questions">${questions.split('|').map(q=>`<li>${q}</li>`).join('')}</ul>${field(id,title,size)}</div>`;}
// Optional resources can contain multiple {label, url} entries per activity.
const activityLinks = {'מדיטציית סליחות':[], 'הליכה מדיטטיבית':[], 'תנועה עדינה':[], 'יוגה קצרה':[], 'ריקוד':[], 'תנועה חופשית':[]};
function options(items){return `<div class="options">${items.map(([title,description])=>`<div class="option"><h5>${title}</h5><p>${description}</p>${(activityLinks[title]||[]).filter(link=>/^https?:\/\//.test(link.url)).map(link=>`<a href="${esc(link.url)}" target="_blank" rel="noopener noreferrer">${esc(link.label)} ↗</a>`).join('')}</div>`).join('')}</div>`;}

function card(n,title,description,content){return `<details><summary><span class="card-number">0${n}</span><span class="card-titles"><h3>${title}</h3><span>${description}</span></span><span class="toggle" aria-hidden="true"></span></summary><div class="card-content">${content}</div></details>`;}
document.querySelector('#evening-cards').innerHTML=[
card(1,'להתכנס ולהסתכל פנימה','להתחיל בנשימה, להתבונן פנימה ולראות את הטוב שהיה.',p('מצאי מקום שנעים לך להיות בו.\nקחי רגע להתמקם.\nעצמי עיניים וקחי שלוש נשימות עמוקות.\nאת לא צריכה להגיע רגועה או מרוכזת במיוחד. פשוט להיות כאן.')+group('given','הטוב שנתתי','איזה טוב עשיתי השנה?|איפה נתתי מעצמי?|עבור מי הייתי שם?|מתי עזרתי, תמכתי או הענקתי בלי לצפות לתמורה?|איזה חלק בעצמי אני שמחה שהבאתי השנה לעולם?','large','בואי נסתכל על הטוב שעשית בשנה האחרונה.')+group('received','הטוב שקיבלתי','איזה טוב עשו עבורי השנה?|מי היה שם בשבילי?|מה קיבלתי מאנשים אחרים?|האם ידעתי להעריך את זה בזמן אמת?|האם יש מישהו שעולה בי עכשיו רצון להודות לו?','large','בואי נסתכל על הטוב שעשו עבורך בשנה האחרונה.')),
card(2,'חשבון נפש','להסתכל בכנות ובקבלה גם על המקומות הפחות פשוטים.',p('בין אם את מאמינה ושומרת ובין אם לא, יש משהו ביום כיפור שמזמין לעצור רגע את מרוץ החיים. דווקא בתחילת שנה חדשה, זו הזדמנות להסתכל פנימה, גם על המקומות שפחות נעים לפגוש.\nלא כדי לשפוט את עצמך, אלא כדי לתת מקום למה שהיה ולפנות מקום לדברים חדשים.')+group('responsibility','איפה הייתי רוצה להיות אחרת?','איפה פעלתי מתוך כעס, פחד, ייאוש או תסכול?|האם פגעתי במישהו?|האם היה רגע שבו ידעתי שאפשר היה לבחור אחרת?|האם יש משהו שאני רוצה לקחת עליו אחריות?|האם יש משהו שאני יכולה או רוצה לתקן?|האם יש מישהו שאני רוצה להתנצל בפניו?')+group('hurt','איפה נפגעתי?','מי או מה פגע בי השנה?|האם אני יכולה להבין מאיפה פעל מי שפגע בי?|האם יש מקום לחמלה למי שפגע בי, גם בלי להצדיק את מה שעשה?|מה עדיין יושב עליי?|מה אני ממשיכה לשחזר בראש?|מה אני לא רוצה להמשיך לסחוב?')+'<aside class="gentle-note"><span class="reminder-label">רק תזכורת</span>להבין לא אומר להסכים.<br>לשחרר לא מחייב לסלוח.<br>וסליחה לא מחייבת לחזור לקשר.</aside>'),
card(3,'להשאיר מאחור ולשחרר','לבחור מה לא ממשיך איתך, ואז לעבור מהראש אל הגוף.',p('אחרי שהסתכלת על מה שהיה, קחי רגע לשאול את עצמך מה את לא רוצה לקחת איתך הלאה.')+'<h4>אני משאירה כאן...</h4>'+p('בואי תיתני מילים לדברים שאת רוצה להשאיר כאן, כדי שלא ימשיכו איתך לשנה הקרובה.')+'<p class="release-prompt">מה הייתי רוצה להניח כאן?</p><p class="examples">כעס · אשמה · פחד · אכזבה · צורך בשליטה<br>סיפור ישן על עצמי · ציפייה שלא התממשה<br>טעות שאני ממשיכה להעניש את עצמי עליה<br>או משהו אחר שאני פשוט עייפה מלסחוב</p>'+field('release','מה הייתי רוצה להניח כאן?','extra-large')+'<div class="body-section"><h4>ועכשיו נעבור לחלק האחרון של התרגול להיום</h4><p class="note">בחרי מה נעים לך עכשיו. את יכולה גם פשוט לשבת כמה רגעים בשקט, לשים לב לנשימה, לתחושות בגוף ולצלילים שסביבך.<br>אפשר לבחור פעילות אחת או לשלב כמה. הקדישי לזה 5-20 דקות, לפי מה שמתאים לך, בלי להעמיס על עצמך.</p>'+options([['מדיטציית סליחות','קחי כמה דקות של שקט ונשימה, ונסי לפגוש את עצמך ברכות.'],['שטיפה במים','אם את בים, את מוזמנת להיכנס לטבילה במים, לנקות מעצמך את הדברים באופן סמלי. אם את בבית, מקלחת גם כן יכולה להיות משחררת.'],['הליכה מדיטטיבית','לכי לאט לאט ושימי לב למגע כפות הרגליים באדמה.'],['תנועה עדינה','שימי מוזיקה נעימה וזוזי כמו שמרגיש לך. את יכולה גם לעשות כמה תנועות ומתיחות שנעימות לגוף, בלי מוזיקה.']])+'</div>')].join('');
document.querySelector('#morning-cards').innerHTML=[
card(1,'להתכנס ולהודות','להתחיל לאט, ולשים לב למה שכבר יש.',p('קחי שלוש נשימות ושימי לב איך את מרגישה הבוקר.\nאת לא חייבת לנתח את מה שהיה אתמול, אבל את יכולה לתת לזה מקום.')+group('gratitude','תודה','על מה אני מודה מהשנה שהייתה?|מי היה משמעותי עבורי?|איזה רגע קטן אני שמחה שהיה לי?|מה בחיים שלי אני נוטה לקחת כמובן מאליו?|על מה אני יכולה להודות לעצמי?','large','במסורת היהודית הבוקר נפתח באמירת תודה. גם כאן, קחי רגע לשים לב למה שיש בחייך ולמה שאת מודה עליו.')),
card(2,'לנוע ולהתעורר','להזיז קצת את הגוף ולשחרר את האווירה.',p('לפני שתעברי למחשבות על השנה הקרובה, קחי רגע להכניס קצת תנועה לגוף.')+options([['יוגה קצרה','בחרי כמה תנוחות מוכרות ותרגלי בקצב הנשימה שלך.'],['ריקוד','שימי שיר שאת אוהבת. עצמי עיניים וזוזי בהתאם למה שמרגיש לך.'],['הליכה','צאי להליכה באוויר הפתוח, בלי יעד ובלי למהר.'],['מתיחות','עשי כמה מתיחות שנעימות לך, כמו תנועות עדינות של הצוואר, הכתפיים והשכמות.'],['תנועה חופשית','שימי לב איך מתחשק לגוף שלך לזוז היום, ותני לו להוביל.']])+p('המטרה היא לא להתאמן.\nרק להוציא קצת אנרגיה, לנער את הכבדות ולהרגיש נוכחת יותר.')+'<h4>רגע להרגיש</h4>'+p('עצרי רגע ושימי לב אם משהו בתחושה בגוף השתנה אחרי התנועה. אם זה עשה לך טוב, אולי תרצי לתת לזה מקום גם בבקרים הבאים. זה בסדר גם אם את מרגישה אותו הדבר.')+field('movement','רגע להרגיש','small')),
card(3,'כוונות לשנה החדשה','לעבור ממה ששחררת אל מה שאת רוצה להזמין לחיים שלך.',group('invite','מה אני רוצה להביא איתי?','איזה טוב שיש בי אני רוצה להביא יותר השנה?|למה אני רוצה לתת יותר מקום?|איך אני רוצה להתייחס לעצמי?|איך אני רוצה להרגיש יותר ביומיום?|אילו אנשים, חוויות או מקומות אני רוצה להכניס יותר לחיים?|מה אני רוצה לטפח?|מה אני רוצה ליצור?|מה אני רוצה להעז?','large','עצרי לשאול את עצמך מה באמת חשוב לך. את לא צריכה להוכיח שום דבר או להכין רשימת מטרות שתצטרכי לעמוד בהן. רק לתת מקום לדברים הטובים שאת רוצה שיהיו בשנה הקרובה.')+'<div class="question-group"><h4>השנה שאני רוצה לחיות</h4>'+p('כתבי בלשון הווה, כאילו את כבר נמצאת בתוך השנה הזאת.\nלא כרשימת יעדים, אלא כתמונה של החיים שאת רוצה לחיות.')+'<div class="starters">'+['אני כאן ברגע הזה ו...','אני מרגישה...','אני מקיפה את עצמי ב...','אני נותנת לעצמי...','אני בוחרת יותר ב...','אני מקדישה זמן ל...','במערכות היחסים שלי...','בעבודה שלי...','בגוף שלי...','אני גאה בעצמי על...','אני מרשה לעצמי...','השנה שלי מרגישה...'].map(x=>`<span>${x}</span>`).join('')+'</div>'+field('year','השנה שאני רוצה לחיות','extra-large')+'</div>')].join('');
document.querySelector('#final-fields').innerHTML=field('takeaway-v3','מה אני רוצה לקחת איתי מהתרגול?','large');
let answers={};let storageOK=true;try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))answers=saved;}catch{storageOK=false;}
const fields=[...document.querySelectorAll('[data-answer]')];
function privacy(){const el=document.querySelector('#storage-warning');el.hidden=storageOK;el.textContent=storageOK?'':'השמירה במכשיר אינה זמינה כרגע. כדי לא לאבד את מה שכתבת, שמרי עותק לפני שתסגרי את העמוד.';}
fields.forEach(el=>{if(typeof answers[el.id]==='string')el.value=answers[el.id];el.addEventListener('input',()=>{answers[el.id]=el.value;try{localStorage.setItem(KEY,JSON.stringify(answers));storageOK=true;}catch{storageOK=false;}privacy();});});privacy();
const modal=document.querySelector('#clear-dialog');document.querySelector('#clear').onclick=()=>modal.showModal();document.querySelector('#cancel').onclick=()=>modal.close();document.querySelector('#confirm-clear').onclick=()=>{try{localStorage.removeItem(KEY);}catch{}answers={};fields.forEach(el=>el.value='');modal.close();document.querySelector('#status').textContent='הכתיבה נמחקה מהמכשיר הזה.';};
let previous=[];function preparePrint(){previous=[...document.querySelectorAll('details')].map(el=>el.open);document.querySelectorAll('details').forEach(el=>el.open=true);fields.forEach(el=>{const copy=document.createElement('div');copy.className='print-answer';copy.textContent=el.value;el.after(copy);});}function finishPrint(){document.querySelectorAll('details').forEach((el,i)=>el.open=previous[i]||false);document.querySelectorAll('.print-answer').forEach(el=>el.remove());}
window.addEventListener('beforeprint',preparePrint);window.addEventListener('afterprint',finishPrint);document.querySelectorAll('.print').forEach(b=>b.onclick=()=>window.print());
